target: pl_modules.cmamba_module.CryptoMambaModule
params: 
    num_features: 6
    hidden_dims: [32, 64, 32, 1]
    d_states: 64
    layer_density: 4
    loss: 'rmse'
    window_size: 32
normalize: False
