CMamba_v1: 'CryptoMamba/v1.yaml'
CMamba_v2: 'CryptoMamba/v2.yaml'
CMamba_v3: 'CryptoMamba/v3.yaml'
CMamba_v4: 'CryptoMamba/v4.yaml'
CMamba_v5: 'CryptoMamba/v5.yaml'
CMamba_v6: 'CryptoMamba/v6.yaml'
CMamba_test: 'CryptoMamba/test.yaml'
LSTM_bi_nv: 'LSTM/lstm_bi_nv.yaml'
LSTM_bi_v: 'LSTM/lstm_bi_v.yaml'
LSTM_nv: 'LSTM/lstm_nv.yaml'
LSTM_v: 'LSTM/lstm_v.yaml'
GRU_nv: 'GRU/gru_nv.yaml'
GRU_v: 'GRU/gru_v.yaml'
SMamba_nv: 'SMamba/smamba_nv.yaml'
SMamba_v: 'SMamba/smamba_v.yaml'
