data_config: 'mode_3'
model: 'CMamba_v6'

name: 'CMamba'
max_epochs: 1100
use_volume: True

hyperparams:
    optimizer: 'adam'
    lr: 0.01
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.001
