data_config: 'mode_3'
model: 'SMamba_v'

name: 'smamba'
max_epochs: 1500
use_volume: True

hyperparams:
    optimizer: 'adam'
    lr: 0.001
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.000003
